import Link from 'next/link';
import {ArrowRight, CheckCircle2, Clock3, Sparkles, Users, Zap} from 'lucide-react';
const people=[['RS','Riya Sharma','React · Next.js · UI/UX','91%'],['AK','Aarav Kumar','Python · ML · FastAPI','88%'],['PS','Priya Singh','Figma · UX Research','86%']];
export default function Home(){return <main>
 <section className="grid-bg border-b border-[#e7e9f2]"><div className="section grid min-h-[620px] items-center gap-14 py-16 md:grid-cols-[1.08fr_.92fr] md:py-24">
  <div><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-[#dfdfff] bg-white px-3 py-2 text-xs font800 text-[#4b4bb9] shadow-sm"><Sparkles size={14}/> AI-powered college collaboration</div><h1 className="max-w-3xl text-5xl font-black leading-[1.04] tracking-[-.045em] md:text-7xl">Build better projects with the <span className="gradient-text">right teammates.</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[#667085] md:text-xl">Tell CampusConnect what you want to build. We help you find students with the right skills, interests, experience and overlapping availability.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/register" className="btn btn-primary px-5 py-3.5">Create your profile <ArrowRight size={17}/></Link><Link href="/discover" className="btn px-5 py-3.5">Explore students</Link></div><div className="mt-8 flex flex-wrap gap-5 text-sm text-[#667085]"><span className="flex items-center gap-2"><CheckCircle2 size={16} className="text-[#12b76a]"/> Skill-based matching</span><span className="flex items-center gap-2"><CheckCircle2 size={16} className="text-[#12b76a]"/> Availability aware</span><span className="flex items-center gap-2"><CheckCircle2 size={16} className="text-[#12b76a]"/> Explainable matches</span></div></div>
  <div className="card relative overflow-hidden p-5 md:p-6"><div className="absolute right-0 top-0 h-32 w-32 rounded-full bg-[#e9e9ff] blur-3xl"/><div className="relative"><div className="flex items-center justify-between"><div><div className="text-sm font-bold">Recommended teammates</div><div className="mt-1 text-xs text-[#98a2b3]">For your Smart Queue project</div></div><span className="pill"><Zap size={13}/> Live matching</span></div><div className="mt-5 space-y-3">{people.map(([i,n,s,m])=><div key={n} className="rounded-2xl border border-[#ececf4] bg-[#fafaff] p-4"><div className="flex items-center gap-3"><div className="avatar h-11 w-11">{i}</div><div className="min-w-0 flex-1"><div className="font-bold">{n}</div><div className="truncate text-xs text-[#667085]">{s}</div></div><div className="text-right"><div className="text-lg font-black text-[#5b5bd6]">{m}</div><div className="text-[10px] font-semibold text-[#98a2b3]">MATCH</div></div></div><div className="mt-3 flex gap-2 text-[11px] text-[#667085]"><span className="rounded-lg bg-white px-2 py-1">✓ Skill coverage</span><span className="rounded-lg bg-white px-2 py-1">✓ Interest overlap</span></div></div>)}</div><div className="mt-4 flex items-center justify-between rounded-2xl bg-[#5b5bd6] px-4 py-3 text-white"><div><div className="text-xs text-white/70">Team compatibility</div><div className="font-bold">Strong project coverage</div></div><Users size={22}/></div></div></div>
 </div></section>
 <section className="section py-16"><div className="grid gap-4 md:grid-cols-3"><div className="card card-hover p-6"><div className="mb-5 flex h-11 w-11 items-center justify-center rounded-xl bg-[#efefff] text-[#5b5bd6]"><Users size={20}/></div><h3 className="text-lg font-black">Find complementary skills</h3><p className="mt-2 text-sm leading-6 text-[#667085]">If your team already has ML, the system can prioritize React, backend or UI/UX talent instead of showing duplicate skills.</p></div><div className="card card-hover p-6"><div className="mb-5 flex h-11 w-11 items-center justify-center rounded-xl bg-[#ecfdf3] text-[#039855]"><Clock3 size={20}/></div><h3 className="text-lg font-black">Match around real schedules</h3><p className="mt-2 text-sm leading-6 text-[#667085]">See overlapping working hours so your teammates can actually collaborate when it matters.</p></div><div className="card card-hover p-6"><div className="mb-5 flex h-11 w-11 items-center justify-center rounded-xl bg-[#fff7ed] text-[#ea580c]"><Sparkles size={20}/></div><h3 className="text-lg font-black">Understand every recommendation</h3><p className="mt-2 text-sm leading-6 text-[#667085]">Every match explains the skills, interests, experience and availability behind the recommendation.</p></div></div></section>
 </main>}
